dest:
    js:     var/www/static/js
    css:    var/www/static/css
    fonts:  var/www/static/fonts
src:
    sass:
        - src/static/css/*.scss
        - src/static/css/**/*.scss
    coffee:
        - src/static/coffee/*.coffee
        - src/static/coffee/**/*.coffee
        - src/static/coffee/**/**/*.coffee
third_party:
    js:
        - src/static/third-party/angular/angular.min.js
        - src/static/third-party/angular-ui-router/release/angular-ui-router.min.js
        - src/static/third-party/angular-bootstrap/ui-bootstrap.min.js
        - src/static/third-party/angular-cookies/angular-cookies.min.js
    css:
        - src/static/third-party/bootstrap/dist/css/bootstrap.min.css
        - src/static/third-party/fontawesome/css/font-awesome.min.css
    fonts:
        - src/static/third-party/bootstrap/dist/fonts/glyphicons-halflings-regular.eot
        - src/static/third-party/bootstrap/dist/fonts/glyphicons-halflings-regular.svg
        - src/static/third-party/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf
        - src/static/third-party/bootstrap/dist/fonts/glyphicons-halflings-regular.woff
        - src/static/third-party/fontawesome/fonts/FontAwesome.otf
        - src/static/third-party/fontawesome/fonts/FontAwesome-webfont.eot
        - src/static/third-party/fontawesome/fonts/FontAwesome-webfont.svg
        - src/static/third-party/fontawesome/fonts/FontAwesome-webfont.ttf
        - src/static/third-party/fontawesome/fonts/FontAwesome-webfont.woff
